### PR TITLE
added ARM Template for creating the alert

### PR DESCRIPTION
**Pull request by JLLudovico**

### CODE REVIEW

**Review by SamVanhoutte — COMMENTED** [review]
Looks good to me. Appreciate the contribution, joao !
The only thing I wonder is if the parameters should be left with those values, or made empty.
Your opinion, @tomkerkhove  ?

**Comment by tomkerkhove** [comment]
I would indeed keep the parameter values empty and suggest to move the files from `alert-azure-api-management-failed-requests-per-api/arm-templates/azuredeploy.json` to `alert-azure-api-management-failed-requests-per-api/azuredeploy.json`, what do you think?

Would keep it a bit simpler.

**Comment by SamVanhoutte** [comment]
@JLLudovico : agree? 

- commit with empty parameter values
- just put it in the same folder as the readme

Muchos gracias !

**Comment by JLLudovico** [comment]
Agree.

Working on it 👍

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Thanks!

**Pull request merged**
